language: python

dist: trusty
sudo: required
group: deprecated-2017Q4  # with new we have some random errors
python: 3.6

install:
  - sudo sh scripts/install_ghdl.sh
  - source ~/.bashrc
  - pip install .

  # only for CI
  - pip install coveralls

script:
  - coverage run --source project -m pytest

after_success:
  - coveralls
