-- generated by pyha 0.0.6
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.PyhaUtil.all;
    use work.Typedefs.all;
    use work.all;
    use work.ComplexSfix_0.all;
    use work.FIR_2.all;


package ComplexFIR_0 is
    type next_t is record
        fir: FIR_2.FIR_2_self_t_list_t(0 to 1);
        DELAY: integer;
        TAPS: Typedefs.sfixed0downto_17_list_t(0 to 7);
    end record;

    type self_t is record
        fir: FIR_2.FIR_2_self_t_list_t(0 to 1);
        DELAY: integer;
        TAPS: Typedefs.sfixed0downto_17_list_t(0 to 7);
        \next\: next_t;
    end record;
    type ComplexFIR_0_self_t_list_t is array (natural range <>) of ComplexFIR_0.self_t;

    procedure \_pyha_init\(self:inout self_t);

    procedure \_pyha_reset_constants\(self:inout self_t);

    procedure \_pyha_reset\(self:inout self_t);

    procedure \_pyha_deepcopy\(self:inout self_t; other: in self_t);

    procedure \_pyha_list_deepcopy\(self:inout ComplexFIR_0_self_t_list_t; other: in ComplexFIR_0_self_t_list_t);

    procedure \_pyha_update_registers\(self:inout self_t);

    procedure main(self:inout self_t; x: ComplexSfix_0.self_t; ret_0:out ComplexSfix_0.self_t);
end package;

package body ComplexFIR_0 is
    procedure \_pyha_init\(self:inout self_t) is
    begin
        FIR_2.\_pyha_init\(self.fir(0));
        FIR_2.\_pyha_init\(self.fir(1));
        self.\next\.DELAY := self.DELAY;
        self.\next\.TAPS := self.TAPS;
    end procedure;

    procedure \_pyha_reset_constants\(self:inout self_t) is
    begin
        self.fir(0).DELAY := 2;
        self.fir(0).TAPS := (Sfix(-0.040802001953125, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(-0.040802001953125, 0, -17));
        self.fir(1).DELAY := 2;
        self.fir(1).TAPS := (Sfix(-0.040802001953125, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(-0.040802001953125, 0, -17));
        self.DELAY := 2;
        self.TAPS := (Sfix(-0.040802001953125, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(-0.040802001953125, 0, -17));
    end procedure;

    procedure \_pyha_reset\(self:inout self_t) is
    begin
        self.fir(0).\next\.DELAY := 2;
        self.fir(0).\next\.TAPS := (Sfix(-0.040802001953125, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(-0.040802001953125, 0, -17));
        self.fir(0).\next\.acc := (Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34));
        self.fir(0).\next\.\out\ := Sfix(0.0, 0, -17);
        self.fir(1).\next\.DELAY := 2;
        self.fir(1).\next\.TAPS := (Sfix(-0.040802001953125, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(-0.040802001953125, 0, -17));
        self.fir(1).\next\.acc := (Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34), Sfix(0.0, 1, -34));
        self.fir(1).\next\.\out\ := Sfix(0.0, 0, -17);
        self.\next\.DELAY := 2;
        self.\next\.TAPS := (Sfix(-0.040802001953125, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.29248046875, 0, -17), Sfix(0.21150970458984375, 0, -17), Sfix(0.1103363037109375, 0, -17), Sfix(-0.040802001953125, 0, -17));
        \_pyha_update_registers\(self);
    end procedure;

    procedure \_pyha_deepcopy\(self:inout self_t; other: in self_t) is
    begin
        self.fir(0).\next\.DELAY := other.fir(0).DELAY;
        self.fir(0).\next\.TAPS := other.fir(0).TAPS;
        self.fir(0).\next\.acc := other.fir(0).acc;
        self.fir(0).\next\.\out\ := other.fir(0).\out\;
        self.fir(1).\next\.DELAY := other.fir(1).DELAY;
        self.fir(1).\next\.TAPS := other.fir(1).TAPS;
        self.fir(1).\next\.acc := other.fir(1).acc;
        self.fir(1).\next\.\out\ := other.fir(1).\out\;
        self.\next\.DELAY := other.DELAY;
        self.\next\.TAPS := other.TAPS;
    end procedure;

    procedure \_pyha_list_deepcopy\(self:inout ComplexFIR_0_self_t_list_t; other: in ComplexFIR_0_self_t_list_t) is
    begin
        for i in self'range loop
            \_pyha_deepcopy\(self(i), other(i));
        end loop;
    end procedure;

    procedure \_pyha_update_registers\(self:inout self_t) is
    begin
        FIR_2.\_pyha_update_registers\(self.fir(0));
        FIR_2.\_pyha_update_registers\(self.fir(1));
    end procedure;

    procedure main(self:inout self_t; x: ComplexSfix_0.self_t; ret_0:out ComplexSfix_0.self_t) is

        variable \out\: ComplexSfix_0.self_t;
    begin
        \out\ := x;
        FIR_2.main(self.fir(0), x.real, ret_0=>\out\.real);
        FIR_2.main(self.fir(1), x.imag, ret_0=>\out\.imag);
        ret_0 := \out\;
        return;
        -- self.outreg = out
        -- return self.outreg
    end procedure;
end package body;
